version: '3.8'

services:
  backend:
    build:
      context: ./user-items-service
      dockerfile: Dockerfile
    container_name: user-items-backend
    ports:
      - "8080:8080"
    volumes:
      - ./user-items-service/src:/app/src
      - ./user-items-service/build.gradle:/app/build.gradle
      - ./user-items-service/settings.gradle:/app/settings.gradle
    networks:
      - app-network

  frontend:
    build:
      context: ./user-items-ui
      dockerfile: Dockerfile
    container_name: user-items-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./user-items-ui:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
